VOCABULARY_MAP = {

    "Volatility":
        "Standard deviation of returns, used as a statistical measure of portfolio risk.",

    "Expected return":
        "Model-based estimate of average annual return used in portfolio optimization.",

    "Allocation":
        "Percentage of total portfolio invested in a given asset.",

    "Diversification":
        "Reduction of total portfolio risk due to imperfect correlation between assets.",

    "Diversification ratio":
        "Ratio of weighted standalone asset volatilities to total portfolio volatility. Higher values indicate stronger diversification.",

    "Concentration":
        "Degree to which portfolio allocation is dominated by a small number of positions.",

    "Risk contribution":
        "Portion of total portfolio volatility attributable to an individual asset.",

    "Correlation":
        "Statistical relationship between asset returns. Lower correlation improves diversification.",

    "Monte Carlo simulation":
        "Simulation of many possible return paths using estimated return and covariance inputs.",

    "Modeled range of outcomes":
        "Range of simulated returns generated by the Monte Carlo model.",

    "Dispersion":
        "Width of the simulated return distribution, indicating how uncertain outcomes are.",

    "Return distribution":
        "Probability distribution of simulated portfolio returns.",

    "Loss probability":
        "Probability that the simulated return over the chosen horizon is negative.",

    "Percentile":
        "Value below which a given percentage of simulation outcomes fall.",

    "Downside limit":
        "User-defined maximum acceptable portfolio volatility constraint.",

    "Weight constraint":
        "Limit on the maximum allocation allowed for a single asset.",

    "Constraint":
        "Restriction applied during optimization, such as weight limits or volatility limits.",
}


def generate_vocabulary(used_terms=None):

    if not used_terms:
        return []

    items = []

    for term in used_terms:
        if term in VOCABULARY_MAP:
            items.append(f"{term} — {VOCABULARY_MAP[term]}")

    return items