ASSET_UNIVERSE = [
    # =========================================================
    # Broad Market ETFs (11)
    # =========================================================
    {"ticker": "SPY", "name": "SPDR S&P 500 ETF Trust", "category": "Broad Market ETFs"},
    {"ticker": "QQQ", "name": "Invesco QQQ Trust", "category": "Broad Market ETFs"},
    {"ticker": "DIA", "name": "SPDR Dow Jones Industrial Average ETF Trust", "category": "Broad Market ETFs"},
    {"ticker": "IWM", "name": "iShares Russell 2000 ETF", "category": "Broad Market ETFs"},
    {"ticker": "VTI", "name": "Vanguard Total Stock Market ETF", "category": "Broad Market ETFs"},
    {"ticker": "VOO", "name": "Vanguard S&P 500 ETF", "category": "Broad Market ETFs"},
    {"ticker": "SCHB", "name": "Schwab U.S. Broad Market ETF", "category": "Broad Market ETFs"},
    {"ticker": "ITOT", "name": "iShares Core S&P Total U.S. Stock Market ETF", "category": "Broad Market ETFs"},
    {"ticker": "RSP", "name": "Invesco S&P 500 Equal Weight ETF", "category": "Broad Market ETFs"},
    {"ticker": "VUG", "name": "Vanguard Growth ETF", "category": "Broad Market ETFs"},
    {"ticker": "VTV", "name": "Vanguard Value ETF", "category": "Broad Market ETFs"},

    # =========================================================
    # International ETFs (11)
    # =========================================================
    {"ticker": "VXUS", "name": "Vanguard Total International Stock ETF", "category": "International ETFs"},
    {"ticker": "VEA", "name": "Vanguard FTSE Developed Markets ETF", "category": "International ETFs"},
    {"ticker": "VWO", "name": "Vanguard FTSE Emerging Markets ETF", "category": "International ETFs"},
    {"ticker": "EWJ", "name": "iShares MSCI Japan ETF", "category": "International ETFs"},
    {"ticker": "EWU", "name": "iShares MSCI United Kingdom ETF", "category": "International ETFs"},
    {"ticker": "EFA", "name": "iShares MSCI EAFE ETF", "category": "International ETFs"},
    {"ticker": "IEFA", "name": "iShares Core MSCI EAFE ETF", "category": "International ETFs"},
    {"ticker": "IXUS", "name": "iShares Core MSCI Total International Stock ETF", "category": "International ETFs"},
    {"ticker": "IEMG", "name": "iShares Core MSCI Emerging Markets ETF", "category": "International ETFs"},
    {"ticker": "EEM", "name": "iShares MSCI Emerging Markets ETF", "category": "International ETFs"},
    {"ticker": "ACWI", "name": "iShares MSCI ACWI ETF", "category": "International ETFs"},

    # =========================================================
    # Bond ETFs (11)
    # =========================================================
    {"ticker": "AGG", "name": "iShares Core U.S. Aggregate Bond ETF", "category": "Bond ETFs"},
    {"ticker": "IEF", "name": "iShares 7-10 Year Treasury Bond ETF", "category": "Bond ETFs"},
    {"ticker": "TLT", "name": "iShares 20+ Year Treasury Bond ETF", "category": "Bond ETFs"},
    {"ticker": "LQD", "name": "iShares iBoxx $ Investment Grade Corporate Bond ETF", "category": "Bond ETFs"},
    {"ticker": "HYG", "name": "iShares iBoxx $ High Yield Corporate Bond ETF", "category": "Bond ETFs"},
    {"ticker": "BND", "name": "Vanguard Total Bond Market ETF", "category": "Bond ETFs"},
    {"ticker": "SHY", "name": "iShares 1-3 Year Treasury Bond ETF", "category": "Bond ETFs"},
    {"ticker": "BIV", "name": "Vanguard Intermediate-Term Bond ETF", "category": "Bond ETFs"},
    {"ticker": "VCIT", "name": "Vanguard Intermediate-Term Corporate Bond ETF", "category": "Bond ETFs"},
    {"ticker": "JNK", "name": "SPDR Bloomberg High Yield Bond ETF", "category": "Bond ETFs"},
    {"ticker": "MUB", "name": "iShares National Muni Bond ETF", "category": "Bond ETFs"},

    # =========================================================
    # Alternative Assets (11)
    # =========================================================
    {"ticker": "GLD", "name": "SPDR Gold Shares", "category": "Alternative Assets"},
    {"ticker": "SLV", "name": "iShares Silver Trust", "category": "Alternative Assets"},
    {"ticker": "DBC", "name": "Invesco DB Commodity Index Tracking Fund", "category": "Alternative Assets"},
    {"ticker": "VNQ", "name": "Vanguard Real Estate ETF", "category": "Alternative Assets"},
    {"ticker": "TIP", "name": "iShares TIPS Bond ETF", "category": "Alternative Assets"},
    {"ticker": "IAU", "name": "iShares Gold Trust", "category": "Alternative Assets"},
    {"ticker": "USO", "name": "United States Oil Fund", "category": "Alternative Assets"},
    {"ticker": "PDBC", "name": "Invesco Optimum Yield Diversified Commodity Strategy No K-1 ETF", "category": "Alternative Assets"},
    {"ticker": "SGOL", "name": "abrdn Physical Gold Shares ETF", "category": "Alternative Assets"},
    {"ticker": "RWR", "name": "SPDR Dow Jones REIT ETF", "category": "Alternative Assets"},
    {"ticker": "COMT", "name": "iShares GSCI Commodity Dynamic Roll Strategy ETF", "category": "Alternative Assets"},

    # =========================================================
    # Sector ETFs (17)
    # =========================================================
    {"ticker": "XLC", "name": "Communication Services Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLY", "name": "Consumer Discretionary Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLP", "name": "Consumer Staples Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLE", "name": "Energy Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLF", "name": "Financial Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLV", "name": "Health Care Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLI", "name": "Industrial Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLB", "name": "Materials Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLRE", "name": "Real Estate Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLK", "name": "Technology Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "XLU", "name": "Utilities Select Sector SPDR Fund", "category": "Sector ETFs"},
    {"ticker": "SMH", "name": "VanEck Semiconductor ETF", "category": "Sector ETFs"},
    {"ticker": "XBI", "name": "SPDR S&P Biotech ETF", "category": "Sector ETFs"},
    {"ticker": "IGV", "name": "iShares Expanded Tech-Software Sector ETF", "category": "Sector ETFs"},
    {"ticker": "XRT", "name": "SPDR S&P Retail ETF", "category": "Sector ETFs"},
    {"ticker": "KBE", "name": "SPDR S&P Bank ETF", "category": "Sector ETFs"},
    {"ticker": "XOP", "name": "SPDR S&P Oil & Gas Exploration & Production ETF", "category": "Sector ETFs"},

    # =========================================================
    # Technology Stocks
    # =========================================================
    {"ticker": "AAPL", "name": "Apple", "category": "Technology Stocks"},
    {"ticker": "MSFT", "name": "Microsoft", "category": "Technology Stocks"},
    {"ticker": "NVDA", "name": "NVIDIA", "category": "Technology Stocks"},
    {"ticker": "AVGO", "name": "Broadcom", "category": "Technology Stocks"},
    {"ticker": "ORCL", "name": "Oracle", "category": "Technology Stocks"},
    {"ticker": "CRM", "name": "Salesforce", "category": "Technology Stocks"},
    {"ticker": "AMD", "name": "Advanced Micro Devices", "category": "Technology Stocks"},
    {"ticker": "CSCO", "name": "Cisco Systems", "category": "Technology Stocks"},
    {"ticker": "TXN", "name": "Texas Instruments", "category": "Technology Stocks"},
    {"ticker": "QCOM", "name": "Qualcomm", "category": "Technology Stocks"},
    {"ticker": "INTU", "name": "Intuit", "category": "Technology Stocks"},
    {"ticker": "IBM", "name": "IBM", "category": "Technology Stocks"},
    {"ticker": "ADBE", "name": "Adobe", "category": "Technology Stocks"},
    {"ticker": "AMAT", "name": "Applied Materials", "category": "Technology Stocks"},
    {"ticker": "MU", "name": "Micron Technology", "category": "Technology Stocks"},
    {"ticker": "NOW", "name": "ServiceNow", "category": "Technology Stocks"},
    {"ticker": "PANW", "name": "Palo Alto Networks", "category": "Technology Stocks"},
    {"ticker": "ANET", "name": "Arista Networks", "category": "Technology Stocks"},
    {"ticker": "KLAC", "name": "KLA", "category": "Technology Stocks"},
    {"ticker": "CDNS", "name": "Cadence Design Systems", "category": "Technology Stocks"},
    {"ticker": "SNOW", "name": "Snowflake", "category": "Technology Stocks"},
    {"ticker": "PLTR", "name": "Palantir", "category": "Technology Stocks"},
    {"ticker": "CRWD", "name": "CrowdStrike", "category": "Technology Stocks"},
    {"ticker": "ZS", "name": "Zscaler", "category": "Technology Stocks"},
    {"ticker": "DDOG", "name": "Datadog", "category": "Technology Stocks"},
    {"ticker": "MDB", "name": "MongoDB", "category": "Technology Stocks"},
    {"ticker": "NET", "name": "Cloudflare", "category": "Technology Stocks"},
    {"ticker": "OKTA", "name": "Okta", "category": "Technology Stocks"},
    {"ticker": "TEAM", "name": "Atlassian", "category": "Technology Stocks"},
    {"ticker": "SHOP", "name": "Shopify", "category": "Technology Stocks"},
    {"ticker": "XYZ", "name": "Block", "category": "Technology Stocks"},
    {"ticker": "U", "name": "Unity Software", "category": "Technology Stocks"},
    {"ticker": "DOCU", "name": "DocuSign", "category": "Technology Stocks"},
    {"ticker": "ROKU", "name": "Roku", "category": "Technology Stocks"},
    {"ticker": "ON", "name": "ON Semiconductor", "category": "Technology Stocks"},
    {"ticker": "MPWR", "name": "Monolithic Power Systems", "category": "Technology Stocks"},
    {"ticker": "LRCX", "name": "Lam Research", "category": "Technology Stocks"},
    {"ticker": "MCHP", "name": "Microchip Technology", "category": "Technology Stocks"},
    {"ticker": "ADI", "name": "Analog Devices", "category": "Technology Stocks"},
    {"ticker": "NXPI", "name": "NXP Semiconductors", "category": "Technology Stocks"},
    {"ticker": "FTNT", "name": "Fortinet", "category": "Technology Stocks"},
    {"ticker": "WDAY", "name": "Workday", "category": "Technology Stocks"},
    {"ticker": "HUBS", "name": "HubSpot", "category": "Technology Stocks"},
    {"ticker": "ESTC", "name": "Elastic", "category": "Technology Stocks"},
    {"ticker": "FSLY", "name": "Fastly", "category": "Technology Stocks"},
    {"ticker": "AKAM", "name": "Akamai Technologies", "category": "Technology Stocks"},
    {"ticker": "TER", "name": "Teradyne", "category": "Technology Stocks"},
    {"ticker": "SWKS", "name": "Skyworks Solutions", "category": "Technology Stocks"},
    {"ticker": "QRVO", "name": "Qorvo", "category": "Technology Stocks"},
    {"ticker": "ENTG", "name": "Entegris", "category": "Technology Stocks"},
    {"ticker": "KEYS", "name": "Keysight Technologies", "category": "Technology Stocks"},
    {"ticker": "IPGP", "name": "IPG Photonics", "category": "Technology Stocks"},
    {"ticker": "FFIV", "name": "F5 Networks", "category": "Technology Stocks"},
    {"ticker": "CIEN", "name": "Ciena", "category": "Technology Stocks"},
    {"ticker": "HPE", "name": "Hewlett Packard Enterprise", "category": "Technology Stocks"},
    {"ticker": "DELL", "name": "Dell Technologies", "category": "Technology Stocks"},
    {"ticker": "HPQ", "name": "HP Inc.", "category": "Technology Stocks"},
    {"ticker": "NTAP", "name": "NetApp", "category": "Technology Stocks"},
    {"ticker": "STX", "name": "Seagate Technology", "category": "Technology Stocks"},
    {"ticker": "WDC", "name": "Western Digital", "category": "Technology Stocks"},
    {"ticker": "COHR", "name": "Coherent Corp.", "category": "Technology Stocks"},
    {"ticker": "MRVL", "name": "Marvell Technology", "category": "Technology Stocks"},
    {"ticker": "TYL", "name": "Tyler Technologies", "category": "Technology Stocks"},
    {"ticker": "PTC", "name": "PTC", "category": "Technology Stocks"},
    # =========================================================
    # Health Care Stocks
    # =========================================================
    {"ticker": "JNJ", "name": "Johnson & Johnson", "category": "Health Care Stocks"},
    {"ticker": "UNH", "name": "UnitedHealth Group", "category": "Health Care Stocks"},
    {"ticker": "LLY", "name": "Eli Lilly", "category": "Health Care Stocks"},
    {"ticker": "ABBV", "name": "AbbVie", "category": "Health Care Stocks"},
    {"ticker": "MRK", "name": "Merck", "category": "Health Care Stocks"},
    {"ticker": "ABT", "name": "Abbott Laboratories", "category": "Health Care Stocks"},
    {"ticker": "TMO", "name": "Thermo Fisher Scientific", "category": "Health Care Stocks"},
    {"ticker": "DHR", "name": "Danaher", "category": "Health Care Stocks"},
    {"ticker": "PFE", "name": "Pfizer", "category": "Health Care Stocks"},
    {"ticker": "BMY", "name": "Bristol-Myers Squibb", "category": "Health Care Stocks"},
    {"ticker": "AMGN", "name": "Amgen", "category": "Health Care Stocks"},
    {"ticker": "ISRG", "name": "Intuitive Surgical", "category": "Health Care Stocks"},
    {"ticker": "GILD", "name": "Gilead Sciences", "category": "Health Care Stocks"},
    {"ticker": "SYK", "name": "Stryker", "category": "Health Care Stocks"},
    {"ticker": "MDT", "name": "Medtronic", "category": "Health Care Stocks"},
    {"ticker": "REGN", "name": "Regeneron Pharmaceuticals", "category": "Health Care Stocks"},
    {"ticker": "BSX", "name": "Boston Scientific", "category": "Health Care Stocks"},
    {"ticker": "CI", "name": "Cigna", "category": "Health Care Stocks"},
    {"ticker": "HUM", "name": "Humana", "category": "Health Care Stocks"},
    {"ticker": "CVS", "name": "CVS Health", "category": "Health Care Stocks"},
    {"ticker": "VRTX", "name": "Vertex Pharmaceuticals", "category": "Health Care Stocks"},
    {"ticker": "ZTS", "name": "Zoetis", "category": "Health Care Stocks"},
    {"ticker": "IDXX", "name": "IDEXX Laboratories", "category": "Health Care Stocks"},
    {"ticker": "ILMN", "name": "Illumina", "category": "Health Care Stocks"},
    {"ticker": "BIIB", "name": "Biogen", "category": "Health Care Stocks"},
    {"ticker": "ALGN", "name": "Align Technology", "category": "Health Care Stocks"},
    {"ticker": "DXCM", "name": "DexCom", "category": "Health Care Stocks"},
    {"ticker": "EW", "name": "Edwards Lifesciences", "category": "Health Care Stocks"},
    {"ticker": "MTD", "name": "Mettler-Toledo", "category": "Health Care Stocks"},
    {"ticker": "IQV", "name": "IQVIA", "category": "Health Care Stocks"},
    {"ticker": "HCA", "name": "HCA Healthcare", "category": "Health Care Stocks"},
    {"ticker": "UHS", "name": "Universal Health Services", "category": "Health Care Stocks"},
    {"ticker": "RMD", "name": "ResMed", "category": "Health Care Stocks"},
    {"ticker": "TECH", "name": "Bio-Techne", "category": "Health Care Stocks"},
    {"ticker": "COO", "name": "Cooper Companies", "category": "Health Care Stocks"},
    {"ticker": "PODD", "name": "Insulet", "category": "Health Care Stocks"},
    {"ticker": "PEN", "name": "Penumbra", "category": "Health Care Stocks"},
    {"ticker": "MASI", "name": "Masimo", "category": "Health Care Stocks"},
    {"ticker": "HOLX", "name": "Hologic", "category": "Health Care Stocks"},
    {"ticker": "BAX", "name": "Baxter International", "category": "Health Care Stocks"},
    {"ticker": "BDX", "name": "Becton Dickinson", "category": "Health Care Stocks"},
    {"ticker": "WST", "name": "West Pharmaceutical Services", "category": "Health Care Stocks"},
    {"ticker": "LH", "name": "Labcorp", "category": "Health Care Stocks"},
    {"ticker": "DGX", "name": "Quest Diagnostics", "category": "Health Care Stocks"},
    {"ticker": "CAH", "name": "Cardinal Health", "category": "Health Care Stocks"},
    {"ticker": "MCK", "name": "McKesson", "category": "Health Care Stocks"},
    {"ticker": "COR", "name": "Cencora", "category": "Health Care Stocks"},
    {"ticker": "INCY", "name": "Incyte", "category": "Health Care Stocks"},
    {"ticker": "NBIX", "name": "Neurocrine Biosciences", "category": "Health Care Stocks"},
    {"ticker": "UTHR", "name": "United Therapeutics", "category": "Health Care Stocks"},
    {"ticker": "ALNY", "name": "Alnylam Pharmaceuticals", "category": "Health Care Stocks"},
    {"ticker": "EXAS", "name": "Exact Sciences", "category": "Health Care Stocks"},
    {"ticker": "VEEV", "name": "Veeva Systems", "category": "Health Care Stocks"},
    {"ticker": "STE", "name": "STERIS", "category": "Health Care Stocks"},
    {"ticker": "BRKR", "name": "Bruker", "category": "Health Care Stocks"},
    {"ticker": "RVTY", "name": "Revvity", "category": "Health Care Stocks"},
    {"ticker": "MEDP", "name": "Medpace", "category": "Health Care Stocks"},
    {"ticker": "MOH", "name": "Molina Healthcare", "category": "Health Care Stocks"},
    {"ticker": "MRNA", "name": "Moderna", "category": "Health Care Stocks"},


    # =========================================================
    # Financial Stocks
    # =========================================================
    {"ticker": "JPM", "name": "JPMorgan Chase", "category": "Financial Stocks"},
    {"ticker": "BAC", "name": "Bank of America", "category": "Financial Stocks"},
    {"ticker": "WFC", "name": "Wells Fargo", "category": "Financial Stocks"},
    {"ticker": "GS", "name": "Goldman Sachs", "category": "Financial Stocks"},
    {"ticker": "MS", "name": "Morgan Stanley", "category": "Financial Stocks"},
    {"ticker": "BLK", "name": "BlackRock", "category": "Financial Stocks"},
    {"ticker": "CME", "name": "CME Group", "category": "Financial Stocks"},
    {"ticker": "ICE", "name": "Intercontinental Exchange", "category": "Financial Stocks"},
    {"ticker": "SCHW", "name": "Charles Schwab", "category": "Financial Stocks"},
    {"ticker": "PGR", "name": "Progressive", "category": "Financial Stocks"},
    {"ticker": "AXP", "name": "American Express", "category": "Financial Stocks"},
    {"ticker": "CB", "name": "Chubb", "category": "Financial Stocks"},
    {"ticker": "USB", "name": "U.S. Bancorp", "category": "Financial Stocks"},
    {"ticker": "TFC", "name": "Truist Financial", "category": "Financial Stocks"},
    {"ticker": "SPGI", "name": "S&P Global", "category": "Financial Stocks"},
    {"ticker": "MCO", "name": "Moody's", "category": "Financial Stocks"},
    {"ticker": "C", "name": "Citigroup", "category": "Financial Stocks"},
    {"ticker": "AON", "name": "Aon", "category": "Financial Stocks"},
    {"ticker": "AJG", "name": "Arthur J. Gallagher & Co.", "category": "Financial Stocks"},
    {"ticker": "BK", "name": "Bank of New York Mellon", "category": "Financial Stocks"},
    {"ticker": "STT", "name": "State Street", "category": "Financial Stocks"},
    {"ticker": "NTRS", "name": "Northern Trust", "category": "Financial Stocks"},
    {"ticker": "MTB", "name": "M&T Bank", "category": "Financial Stocks"},
    {"ticker": "FITB", "name": "Fifth Third Bancorp", "category": "Financial Stocks"},
    {"ticker": "HBAN", "name": "Huntington Bancshares", "category": "Financial Stocks"},
    {"ticker": "RF", "name": "Regions Financial", "category": "Financial Stocks"},
    {"ticker": "CFG", "name": "Citizens Financial Group", "category": "Financial Stocks"},
    {"ticker": "ALLY", "name": "Ally Financial", "category": "Financial Stocks"},
    {"ticker": "COF", "name": "Capital One", "category": "Financial Stocks"},
    {"ticker": "TRV", "name": "Travelers", "category": "Financial Stocks"},
    {"ticker": "ALL", "name": "Allstate", "category": "Financial Stocks"},
    {"ticker": "MET", "name": "MetLife", "category": "Financial Stocks"},
    {"ticker": "PRU", "name": "Prudential Financial", "category": "Financial Stocks"},
    {"ticker": "AFL", "name": "Aflac", "category": "Financial Stocks"},
    {"ticker": "SYF", "name": "Synchrony Financial", "category": "Financial Stocks"},
    {"ticker": "KEY", "name": "KeyCorp", "category": "Financial Stocks"},
    {"ticker": "PNC", "name": "PNC Financial Services", "category": "Financial Stocks"},
    {"ticker": "ZION", "name": "Zions Bancorporation", "category": "Financial Stocks"},
    {"ticker": "CINF", "name": "Cincinnati Financial", "category": "Financial Stocks"},
    {"ticker": "WRB", "name": "W.R. Berkley", "category": "Financial Stocks"},
    {"ticker": "MKL", "name": "Markel", "category": "Financial Stocks"},
    {"ticker": "RJF", "name": "Raymond James Financial", "category": "Financial Stocks"},
    {"ticker": "BEN", "name": "Franklin Resources", "category": "Financial Stocks"},
    {"ticker": "IVZ", "name": "Invesco", "category": "Financial Stocks"},
    {"ticker": "TROW", "name": "T. Rowe Price", "category": "Financial Stocks"},
    {"ticker": "AMP", "name": "Ameriprise Financial", "category": "Financial Stocks"},
    {"ticker": "LPLA", "name": "LPL Financial", "category": "Financial Stocks"},
    {"ticker": "CBOE", "name": "Cboe Global Markets", "category": "Financial Stocks"},
    {"ticker": "NDAQ", "name": "Nasdaq", "category": "Financial Stocks"},
    {"ticker": "AIZ", "name": "Assurant", "category": "Financial Stocks"},
    {"ticker": "FDS", "name": "FactSet", "category": "Financial Stocks"},
    {"ticker": "MSCI", "name": "MSCI Inc.", "category": "Financial Stocks"},
    {"ticker": "BRO", "name": "Brown & Brown", "category": "Financial Stocks"},
    {"ticker": "PFG", "name": "Principal Financial Group", "category": "Financial Stocks"},
    {"ticker": "RGA", "name": "Reinsurance Group of America", "category": "Financial Stocks"},

    # =========================================================
    # Industrial Stocks
    # =========================================================
    {"ticker": "CAT", "name": "Caterpillar", "category": "Industrial Stocks"},
    {"ticker": "HON", "name": "Honeywell", "category": "Industrial Stocks"},
    {"ticker": "GE", "name": "GE Aerospace", "category": "Industrial Stocks"},
    {"ticker": "RTX", "name": "RTX", "category": "Industrial Stocks"},
    {"ticker": "DE", "name": "Deere", "category": "Industrial Stocks"},
    {"ticker": "UPS", "name": "United Parcel Service", "category": "Industrial Stocks"},
    {"ticker": "LMT", "name": "Lockheed Martin", "category": "Industrial Stocks"},
    {"ticker": "WM", "name": "Waste Management", "category": "Industrial Stocks"},
    {"ticker": "ETN", "name": "Eaton", "category": "Industrial Stocks"},
    {"ticker": "PH", "name": "Parker-Hannifin", "category": "Industrial Stocks"},
    {"ticker": "ADP", "name": "Automatic Data Processing", "category": "Industrial Stocks"},
    {"ticker": "EMR", "name": "Emerson Electric", "category": "Industrial Stocks"},
    {"ticker": "UNP", "name": "Union Pacific", "category": "Industrial Stocks"},
    {"ticker": "NSC", "name": "Norfolk Southern", "category": "Industrial Stocks"},
    {"ticker": "GD", "name": "General Dynamics", "category": "Industrial Stocks"},
    {"ticker": "NOC", "name": "Northrop Grumman", "category": "Industrial Stocks"},
    {"ticker": "TT", "name": "Trane Technologies", "category": "Industrial Stocks"},
    {"ticker": "RSG", "name": "Republic Services", "category": "Industrial Stocks"},
    {"ticker": "CARR", "name": "Carrier Global", "category": "Industrial Stocks"},
    {"ticker": "FAST", "name": "Fastenal", "category": "Industrial Stocks"},
    {"ticker": "JCI", "name": "Johnson Controls", "category": "Industrial Stocks"},
    {"ticker": "ITW", "name": "Illinois Tool Works", "category": "Industrial Stocks"},
    {"ticker": "DOV", "name": "Dover", "category": "Industrial Stocks"},
    {"ticker": "XYL", "name": "Xylem", "category": "Industrial Stocks"},
    {"ticker": "IR", "name": "Ingersoll Rand", "category": "Industrial Stocks"},
    {"ticker": "AME", "name": "AMETEK", "category": "Industrial Stocks"},
    {"ticker": "ROK", "name": "Rockwell Automation", "category": "Industrial Stocks"},
    {"ticker": "LHX", "name": "L3Harris Technologies", "category": "Industrial Stocks"},
    {"ticker": "TDG", "name": "TransDigm", "category": "Industrial Stocks"},
    {"ticker": "HEI", "name": "HEICO", "category": "Industrial Stocks"},
    {"ticker": "WAB", "name": "Wabtec", "category": "Industrial Stocks"},
    {"ticker": "CHRW", "name": "C.H. Robinson", "category": "Industrial Stocks"},
    {"ticker": "JBHT", "name": "J.B. Hunt", "category": "Industrial Stocks"},
    {"ticker": "EXPD", "name": "Expeditors International", "category": "Industrial Stocks"},
    {"ticker": "ODFL", "name": "Old Dominion Freight Line", "category": "Industrial Stocks"},
    {"ticker": "PCAR", "name": "PACCAR", "category": "Industrial Stocks"},
    {"ticker": "URI", "name": "United Rentals", "category": "Industrial Stocks"},
    {"ticker": "MTZ", "name": "MasTec", "category": "Industrial Stocks"},
    {"ticker": "PWR", "name": "Quanta Services", "category": "Industrial Stocks"},
    {"ticker": "GWW", "name": "W.W. Grainger", "category": "Industrial Stocks"},
    {"ticker": "CSL", "name": "Carlisle Companies", "category": "Industrial Stocks"},
    {"ticker": "HUBB", "name": "Hubbell", "category": "Industrial Stocks"},
    {"ticker": "NDSN", "name": "Nordson", "category": "Industrial Stocks"},
    {"ticker": "AOS", "name": "A.O. Smith", "category": "Industrial Stocks"},
    {"ticker": "BLDR", "name": "Builders FirstSource", "category": "Industrial Stocks"},
    {"ticker": "MLI", "name": "Mueller Industries", "category": "Industrial Stocks"},
    {"ticker": "GNRC", "name": "Generac", "category": "Industrial Stocks"},
    {"ticker": "KBR", "name": "KBR", "category": "Industrial Stocks"},
    {"ticker": "FLR", "name": "Fluor", "category": "Industrial Stocks"},
    {"ticker": "J", "name": "Jacobs Solutions", "category": "Industrial Stocks"},
    {"ticker": "SAIA", "name": "Saia", "category": "Industrial Stocks"},
    {"ticker": "KNX", "name": "Knight-Swift Transportation", "category": "Industrial Stocks"},
    {"ticker": "LSTR", "name": "Landstar System", "category": "Industrial Stocks"},
    {"ticker": "WMS", "name": "Advanced Drainage Systems", "category": "Industrial Stocks"},
    {"ticker": "TREX", "name": "Trex Company", "category": "Industrial Stocks"},
    {"ticker": "FIX", "name": "Comfort Systems USA", "category": "Industrial Stocks"},
    {"ticker": "RHI", "name": "Robert Half", "category": "Industrial Stocks"},
    {"ticker": "APTV", "name": "Aptiv", "category": "Industrial Stocks"},

    # =========================================================
    # Consumer Discretionary Stocks
    # =========================================================
    {"ticker": "AMZN", "name": "Amazon", "category": "Consumer Discretionary Stocks"},
    {"ticker": "TSLA", "name": "Tesla", "category": "Consumer Discretionary Stocks"},
    {"ticker": "HD", "name": "Home Depot", "category": "Consumer Discretionary Stocks"},
    {"ticker": "MCD", "name": "McDonald's", "category": "Consumer Discretionary Stocks"},
    {"ticker": "NKE", "name": "Nike", "category": "Consumer Discretionary Stocks"},
    {"ticker": "SBUX", "name": "Starbucks", "category": "Consumer Discretionary Stocks"},
    {"ticker": "BKNG", "name": "Booking Holdings", "category": "Consumer Discretionary Stocks"},
    {"ticker": "LOW", "name": "Lowe's", "category": "Consumer Discretionary Stocks"},
    {"ticker": "TJX", "name": "TJX Companies", "category": "Consumer Discretionary Stocks"},
    {"ticker": "MAR", "name": "Marriott International", "category": "Consumer Discretionary Stocks"},
    {"ticker": "CMG", "name": "Chipotle Mexican Grill", "category": "Consumer Discretionary Stocks"},
    {"ticker": "ROST", "name": "Ross Stores", "category": "Consumer Discretionary Stocks"},
    {"ticker": "ORLY", "name": "O'Reilly Automotive", "category": "Consumer Discretionary Stocks"},
    {"ticker": "AZO", "name": "AutoZone", "category": "Consumer Discretionary Stocks"},
    {"ticker": "EBAY", "name": "eBay", "category": "Consumer Discretionary Stocks"},
    {"ticker": "YUM", "name": "Yum! Brands", "category": "Consumer Discretionary Stocks"},
    {"ticker": "DRI", "name": "Darden Restaurants", "category": "Consumer Discretionary Stocks"},
    {"ticker": "LEN", "name": "Lennar", "category": "Consumer Discretionary Stocks"},
    {"ticker": "F", "name": "Ford Motor", "category": "Consumer Discretionary Stocks"},
    {"ticker": "GM", "name": "General Motors", "category": "Consumer Discretionary Stocks"},
    {"ticker": "ABNB", "name": "Airbnb", "category": "Consumer Discretionary Stocks"},
    {"ticker": "UBER", "name": "Uber", "category": "Consumer Discretionary Stocks"},
    {"ticker": "LYFT", "name": "Lyft", "category": "Consumer Discretionary Stocks"},
    {"ticker": "RCL", "name": "Royal Caribbean", "category": "Consumer Discretionary Stocks"},
    {"ticker": "CCL", "name": "Carnival", "category": "Consumer Discretionary Stocks"},
    {"ticker": "NCLH", "name": "Norwegian Cruise Line", "category": "Consumer Discretionary Stocks"},
    {"ticker": "LULU", "name": "Lululemon", "category": "Consumer Discretionary Stocks"},
    {"ticker": "ULTA", "name": "Ulta Beauty", "category": "Consumer Discretionary Stocks"},
    {"ticker": "ETSY", "name": "Etsy", "category": "Consumer Discretionary Stocks"},
    {"ticker": "PENN", "name": "Penn Entertainment", "category": "Consumer Discretionary Stocks"},
    {"ticker": "DKNG", "name": "DraftKings", "category": "Consumer Discretionary Stocks"},
    {"ticker": "WYNN", "name": "Wynn Resorts", "category": "Consumer Discretionary Stocks"},
    {"ticker": "MGM", "name": "MGM Resorts", "category": "Consumer Discretionary Stocks"},
    {"ticker": "HAS", "name": "Hasbro", "category": "Consumer Discretionary Stocks"},
    {"ticker": "MAT", "name": "Mattel", "category": "Consumer Discretionary Stocks"},
    {"ticker": "WSM", "name": "Williams-Sonoma", "category": "Consumer Discretionary Stocks"},
    {"ticker": "RH", "name": "RH", "category": "Consumer Discretionary Stocks"},
    {"ticker": "FIVE", "name": "Five Below", "category": "Consumer Discretionary Stocks"},
    {"ticker": "BURL", "name": "Burlington Stores", "category": "Consumer Discretionary Stocks"},
    {"ticker": "DKS", "name": "Dick's Sporting Goods", "category": "Consumer Discretionary Stocks"},
    {"ticker": "BBY", "name": "Best Buy", "category": "Consumer Discretionary Stocks"},
    {"ticker": "AAP", "name": "Advance Auto Parts", "category": "Consumer Discretionary Stocks"},
    {"ticker": "GPC", "name": "Genuine Parts Company", "category": "Consumer Discretionary Stocks"},
    {"ticker": "TPR", "name": "Tapestry", "category": "Consumer Discretionary Stocks"},
    {"ticker": "RL", "name": "Ralph Lauren", "category": "Consumer Discretionary Stocks"},
    {"ticker": "PVH", "name": "PVH Corp.", "category": "Consumer Discretionary Stocks"},
    {"ticker": "LEVI", "name": "Levi Strauss", "category": "Consumer Discretionary Stocks"},
    {"ticker": "VFC", "name": "VF Corporation", "category": "Consumer Discretionary Stocks"},
    {"ticker": "HOG", "name": "Harley-Davidson", "category": "Consumer Discretionary Stocks"},
    {"ticker": "NVR", "name": "NVR Inc.", "category": "Consumer Discretionary Stocks"},
    {"ticker": "DHI", "name": "D.R. Horton", "category": "Consumer Discretionary Stocks"},
    {"ticker": "PHM", "name": "PulteGroup", "category": "Consumer Discretionary Stocks"},
    {"ticker": "YETI", "name": "YETI Holdings", "category": "Consumer Discretionary Stocks"},
    {"ticker": "CZR", "name": "Caesars Entertainment", "category": "Consumer Discretionary Stocks"},
    {"ticker": "POOL", "name": "Pool Corporation", "category": "Consumer Discretionary Stocks"},
    {"ticker": "MHK", "name": "Mohawk Industries", "category": "Consumer Discretionary Stocks"},
    {"ticker": "DECK", "name": "Deckers Outdoor", "category": "Consumer Discretionary Stocks"},
    {"ticker": "LKQ", "name": "LKQ", "category": "Consumer Discretionary Stocks"},


    # =========================================================
    # Consumer Staples Stocks
    # =========================================================
    {"ticker": "PG", "name": "Procter & Gamble", "category": "Consumer Staples Stocks"},
    {"ticker": "KO", "name": "Coca-Cola", "category": "Consumer Staples Stocks"},
    {"ticker": "PEP", "name": "PepsiCo", "category": "Consumer Staples Stocks"},
    {"ticker": "COST", "name": "Costco", "category": "Consumer Staples Stocks"},
    {"ticker": "WMT", "name": "Walmart", "category": "Consumer Staples Stocks"},
    {"ticker": "PM", "name": "Philip Morris International", "category": "Consumer Staples Stocks"},
    {"ticker": "MO", "name": "Altria", "category": "Consumer Staples Stocks"},
    {"ticker": "CL", "name": "Colgate-Palmolive", "category": "Consumer Staples Stocks"},
    {"ticker": "MDLZ", "name": "Mondelez International", "category": "Consumer Staples Stocks"},
    {"ticker": "GIS", "name": "General Mills", "category": "Consumer Staples Stocks"},
    {"ticker": "KMB", "name": "Kimberly-Clark", "category": "Consumer Staples Stocks"},
    {"ticker": "KR", "name": "Kroger", "category": "Consumer Staples Stocks"},
    {"ticker": "SYY", "name": "Sysco", "category": "Consumer Staples Stocks"},
    {"ticker": "HSY", "name": "Hershey", "category": "Consumer Staples Stocks"},
    {"ticker": "MNST", "name": "Monster Beverage", "category": "Consumer Staples Stocks"},
    {"ticker": "KHC", "name": "Kraft Heinz", "category": "Consumer Staples Stocks"},
    {"ticker": "DG", "name": "Dollar General", "category": "Consumer Staples Stocks"},
    {"ticker": "DLTR", "name": "Dollar Tree", "category": "Consumer Staples Stocks"},
    {"ticker": "ADM", "name": "Archer-Daniels-Midland", "category": "Consumer Staples Stocks"},
    {"ticker": "CHD", "name": "Church & Dwight", "category": "Consumer Staples Stocks"},
    {"ticker": "TSN", "name": "Tyson Foods", "category": "Consumer Staples Stocks"},
    {"ticker": "EL", "name": "Estée Lauder", "category": "Consumer Staples Stocks"},
    {"ticker": "CPB", "name": "Campbell's", "category": "Consumer Staples Stocks"},

        # =========================================================
    # Energy Stocks
    # =========================================================
    {"ticker": "XOM", "name": "Exxon Mobil", "category": "Energy Stocks"},
    {"ticker": "CVX", "name": "Chevron", "category": "Energy Stocks"},
    {"ticker": "COP", "name": "ConocoPhillips", "category": "Energy Stocks"},
    {"ticker": "SLB", "name": "Schlumberger", "category": "Energy Stocks"},
    {"ticker": "EOG", "name": "EOG Resources", "category": "Energy Stocks"},
    {"ticker": "MPC", "name": "Marathon Petroleum", "category": "Energy Stocks"},
    {"ticker": "PSX", "name": "Phillips 66", "category": "Energy Stocks"},
    {"ticker": "VLO", "name": "Valero Energy", "category": "Energy Stocks"},
    {"ticker": "OXY", "name": "Occidental Petroleum", "category": "Energy Stocks"},
    {"ticker": "KMI", "name": "Kinder Morgan", "category": "Energy Stocks"},
    {"ticker": "HAL", "name": "Halliburton", "category": "Energy Stocks"},
    {"ticker": "DVN", "name": "Devon Energy", "category": "Energy Stocks"},
    {"ticker": "APA", "name": "APA Corporation", "category": "Energy Stocks"},
    {"ticker": "FANG", "name": "Diamondback Energy", "category": "Energy Stocks"},
    {"ticker": "CTRA", "name": "Coterra Energy", "category": "Energy Stocks"},
    {"ticker": "BKR", "name": "Baker Hughes", "category": "Energy Stocks"},
    {"ticker": "WMB", "name": "Williams Companies", "category": "Energy Stocks"},
    {"ticker": "EQT", "name": "EQT Corporation", "category": "Energy Stocks"},
    {"ticker": "OKE", "name": "ONEOK", "category": "Energy Stocks"},
    {"ticker": "EXE", "name": "Expand Energy", "category": "Energy Stocks"},
    {"ticker": "AR", "name": "Antero Resources", "category": "Energy Stocks"},
    {"ticker": "TRGP", "name": "Targa Resources", "category": "Energy Stocks"},
    {"ticker": "MPLX", "name": "MPLX LP", "category": "Energy Stocks"},
    {"ticker": "EPD", "name": "Enterprise Products Partners", "category": "Energy Stocks"},
    {"ticker": "ET", "name": "Energy Transfer", "category": "Energy Stocks"},
    {"ticker": "PAA", "name": "Plains All American Pipeline", "category": "Energy Stocks"},
    {"ticker": "ENB", "name": "Enbridge", "category": "Energy Stocks"},
    {"ticker": "TRP", "name": "TC Energy", "category": "Energy Stocks"},
    {"ticker": "SU", "name": "Suncor Energy", "category": "Energy Stocks"},
    {"ticker": "CNQ", "name": "Canadian Natural Resources", "category": "Energy Stocks"},
    {"ticker": "IMO", "name": "Imperial Oil", "category": "Energy Stocks"},
    {"ticker": "OVV", "name": "Ovintiv", "category": "Energy Stocks"},
    {"ticker": "PR", "name": "Permian Resources", "category": "Energy Stocks"},
    {"ticker": "CHRD", "name": "Chord Energy", "category": "Energy Stocks"},
    # =========================================================
    # Materials Stocks
    # =========================================================
    {"ticker": "LIN", "name": "Linde", "category": "Materials Stocks"},
    {"ticker": "SHW", "name": "Sherwin-Williams", "category": "Materials Stocks"},
    {"ticker": "APD", "name": "Air Products and Chemicals", "category": "Materials Stocks"},
    {"ticker": "FCX", "name": "Freeport-McMoRan", "category": "Materials Stocks"},
    {"ticker": "NEM", "name": "Newmont", "category": "Materials Stocks"},
    {"ticker": "DD", "name": "DuPont", "category": "Materials Stocks"},
    {"ticker": "ECL", "name": "Ecolab", "category": "Materials Stocks"},
    {"ticker": "MLM", "name": "Martin Marietta Materials", "category": "Materials Stocks"},
    {"ticker": "NUE", "name": "Nucor", "category": "Materials Stocks"},
    {"ticker": "ALB", "name": "Albemarle", "category": "Materials Stocks"},
    {"ticker": "LYB", "name": "LyondellBasell", "category": "Materials Stocks"},
    {"ticker": "IP", "name": "International Paper", "category": "Materials Stocks"},
    {"ticker": "VMC", "name": "Vulcan Materials", "category": "Materials Stocks"},
    {"ticker": "STLD", "name": "Steel Dynamics", "category": "Materials Stocks"},
    {"ticker": "CF", "name": "CF Industries", "category": "Materials Stocks"},
    {"ticker": "BALL", "name": "Ball Corporation", "category": "Materials Stocks"},
    {"ticker": "PKG", "name": "Packaging Corporation of America", "category": "Materials Stocks"},
    {"ticker": "AVY", "name": "Avery Dennison", "category": "Materials Stocks"},
    {"ticker": "CE", "name": "Celanese", "category": "Materials Stocks"},
    {"ticker": "EMN", "name": "Eastman Chemical", "category": "Materials Stocks"},
    {"ticker": "OLN", "name": "Olin", "category": "Materials Stocks"},
    {"ticker": "MOS", "name": "Mosaic", "category": "Materials Stocks"},
    {"ticker": "FMC", "name": "FMC Corporation", "category": "Materials Stocks"},
    {"ticker": "CLF", "name": "Cleveland-Cliffs", "category": "Materials Stocks"},
    {"ticker": "AA", "name": "Alcoa", "category": "Materials Stocks"},
    {"ticker": "CMC", "name": "Commercial Metals", "category": "Materials Stocks"},
    {"ticker": "RS", "name": "Reliance Steel", "category": "Materials Stocks"},
    {"ticker": "MP", "name": "MP Materials", "category": "Materials Stocks"},
    {"ticker": "IFF", "name": "International Flavors & Fragrances", "category": "Materials Stocks"},
    {"ticker": "CCK", "name": "Crown Holdings", "category": "Materials Stocks"},
    {"ticker": "SEE", "name": "Sealed Air", "category": "Materials Stocks"},
    {"ticker": "SON", "name": "Sonoco Products", "category": "Materials Stocks"},


    # =========================================================
    # Utilities Stocks
    # =========================================================
    {"ticker": "NEE", "name": "NextEra Energy", "category": "Utilities Stocks"},
    {"ticker": "SO", "name": "Southern Company", "category": "Utilities Stocks"},
    {"ticker": "DUK", "name": "Duke Energy", "category": "Utilities Stocks"},
    {"ticker": "AEP", "name": "American Electric Power", "category": "Utilities Stocks"},
    {"ticker": "EXC", "name": "Exelon", "category": "Utilities Stocks"},
    {"ticker": "XEL", "name": "Xcel Energy", "category": "Utilities Stocks"},
    {"ticker": "SRE", "name": "Sempra", "category": "Utilities Stocks"},
    {"ticker": "EIX", "name": "Edison International", "category": "Utilities Stocks"},
    {"ticker": "ED", "name": "Consolidated Edison", "category": "Utilities Stocks"},
    {"ticker": "PEG", "name": "Public Service Enterprise Group", "category": "Utilities Stocks"},
    {"ticker": "D", "name": "Dominion Energy", "category": "Utilities Stocks"},
    {"ticker": "AWK", "name": "American Water Works", "category": "Utilities Stocks"},
    {"ticker": "NRG", "name": "NRG Energy", "category": "Utilities Stocks"},
    {"ticker": "AES", "name": "AES Corporation", "category": "Utilities Stocks"},
    {"ticker": "CMS", "name": "CMS Energy", "category": "Utilities Stocks"},
    {"ticker": "DTE", "name": "DTE Energy", "category": "Utilities Stocks"},
    {"ticker": "WEC", "name": "WEC Energy Group", "category": "Utilities Stocks"},
    {"ticker": "ES", "name": "Eversource Energy", "category": "Utilities Stocks"},
    {"ticker": "FE", "name": "FirstEnergy", "category": "Utilities Stocks"},
    {"ticker": "ATO", "name": "Atmos Energy", "category": "Utilities Stocks"},
    {"ticker": "NI", "name": "NiSource", "category": "Utilities Stocks"},
    {"ticker": "PNW", "name": "Pinnacle West", "category": "Utilities Stocks"},

    # =========================================================
    # Real Estate Stocks
    # =========================================================
    {"ticker": "PLD", "name": "Prologis", "category": "Real Estate Stocks"},
    {"ticker": "AMT", "name": "American Tower", "category": "Real Estate Stocks"},
    {"ticker": "EQIX", "name": "Equinix", "category": "Real Estate Stocks"},
    {"ticker": "O", "name": "Realty Income", "category": "Real Estate Stocks"},
    {"ticker": "CCI", "name": "Crown Castle", "category": "Real Estate Stocks"},
    {"ticker": "WELL", "name": "Welltower", "category": "Real Estate Stocks"},
    {"ticker": "PSA", "name": "Public Storage", "category": "Real Estate Stocks"},
    {"ticker": "SPG", "name": "Simon Property Group", "category": "Real Estate Stocks"},
    {"ticker": "DLR", "name": "Digital Realty Trust", "category": "Real Estate Stocks"},
    {"ticker": "VICI", "name": "VICI Properties", "category": "Real Estate Stocks"},
    {"ticker": "AVB", "name": "AvalonBay Communities", "category": "Real Estate Stocks"},
    {"ticker": "EQR", "name": "Equity Residential", "category": "Real Estate Stocks"},
    {"ticker": "ARE", "name": "Alexandria Real Estate", "category": "Real Estate Stocks"},
    {"ticker": "BXP", "name": "Boston Properties", "category": "Real Estate Stocks"},
    {"ticker": "HST", "name": "Host Hotels & Resorts", "category": "Real Estate Stocks"},
    {"ticker": "REG", "name": "Regency Centers", "category": "Real Estate Stocks"},
    {"ticker": "FRT", "name": "Federal Realty Investment Trust", "category": "Real Estate Stocks"},
    {"ticker": "KIM", "name": "Kimco Realty", "category": "Real Estate Stocks"},
    {"ticker": "UDR", "name": "UDR Inc.", "category": "Real Estate Stocks"},
    {"ticker": "MAA", "name": "Mid-America Apartment Communities", "category": "Real Estate Stocks"},
    {"ticker": "ESS", "name": "Essex Property Trust", "category": "Real Estate Stocks"},
    {"ticker": "CPT", "name": "Camden Property Trust", "category": "Real Estate Stocks"},
    {"ticker": "INVH", "name": "Invitation Homes", "category": "Real Estate Stocks"},
    {"ticker": "IRM", "name": "Iron Mountain", "category": "Real Estate Stocks"},
    {"ticker": "SBAC", "name": "SBA Communications", "category": "Real Estate Stocks"},
    {"ticker": "DOC", "name": "Healthpeak Properties", "category": "Real Estate Stocks"},
    # =========================================================
    # Communication Services Stocks
    # =========================================================
    {"ticker": "GOOGL", "name": "Alphabet", "category": "Communication Services Stocks"},
    {"ticker": "META", "name": "Meta Platforms", "category": "Communication Services Stocks"},
    {"ticker": "NFLX", "name": "Netflix", "category": "Communication Services Stocks"},
    {"ticker": "TMUS", "name": "T-Mobile US", "category": "Communication Services Stocks"},
    {"ticker": "DIS", "name": "Walt Disney", "category": "Communication Services Stocks"},
    {"ticker": "T", "name": "AT&T", "category": "Communication Services Stocks"},
    {"ticker": "CMCSA", "name": "Comcast", "category": "Communication Services Stocks"},
    {"ticker": "CHTR", "name": "Charter Communications", "category": "Communication Services Stocks"},
    {"ticker": "VZ", "name": "Verizon Communications", "category": "Communication Services Stocks"},
    {"ticker": "WBD", "name": "Warner Bros. Discovery", "category": "Communication Services Stocks"},
    {"ticker": "RBLX", "name": "Roblox", "category": "Communication Services Stocks"},
    {"ticker": "FOXA", "name": "Fox Corporation", "category": "Communication Services Stocks"},
    {"ticker": "FOX", "name": "Fox Corporation Class B", "category": "Communication Services Stocks"},
    {"ticker": "MTCH", "name": "Match Group", "category": "Communication Services Stocks"},
    {"ticker": "SNAP", "name": "Snap", "category": "Communication Services Stocks"},
    {"ticker": "PINS", "name": "Pinterest", "category": "Communication Services Stocks"},
    {"ticker": "TTWO", "name": "Take-Two Interactive", "category": "Communication Services Stocks"},
    {"ticker": "EA", "name": "Electronic Arts", "category": "Communication Services Stocks"},
    {"ticker": "LYV", "name": "Live Nation Entertainment", "category": "Communication Services Stocks"},
    {"ticker": "OMC", "name": "Omnicom Group", "category": "Communication Services Stocks"},
    {"ticker": "SPOT", "name": "Spotify Technology", "category": "Communication Services Stocks"},
    {"ticker": "TME", "name": "Tencent Music Entertainment", "category": "Communication Services Stocks"},
    {"ticker": "BIDU", "name": "Baidu", "category": "Communication Services Stocks"},
    ]

TICKERS = [asset["ticker"] for asset in ASSET_UNIVERSE]

TICKER_TO_NAME = {asset["ticker"]: asset["name"] for asset in ASSET_UNIVERSE}

TICKER_TO_CATEGORY = {asset["ticker"]: asset["category"] for asset in ASSET_UNIVERSE}

START_DATE = "2020-01-01"

EXPECTED_RETURN_METHOD = "equilibrium_blended"
EXPECTED_RETURN_BLEND_WEIGHT = 0.50
EXPECTED_RETURN_SPAN = 180
EXPECTED_RETURN_SIGNAL_WEIGHT = 0.50

MIN_EXPECTED_RETURN = 0.02
MAX_EXPECTED_RETURN = 0.25
BASELINE_EXPECTED_RETURN = 0.08

CATEGORY_BASELINE_RETURNS = {
    "Technology Stocks": 0.12,
    "Health Care Stocks": 0.10,
    "Financial Stocks": 0.10,
    "Industrial Stocks": 0.10,
    "Consumer Discretionary Stocks": 0.11,
    "Consumer Staples Stocks": 0.08,
    "Energy Stocks": 0.10,
    "Materials Stocks": 0.09,
    "Utilities Stocks": 0.07,
    "Real Estate Stocks": 0.08,
    "Communication Services Stocks": 0.11,
    "Broad Market ETFs": 0.10,
    "Sector ETFs": 0.10,
    "International ETFs": 0.09,
    "Bond ETFs": 0.05,
    "Alternative Assets": 0.05,
}

OPTIMIZER_REGULARIZATION_STRENGTH = 0.07

MIN_WEIGHT_BOUND = 0.0
MAX_WEIGHT_BOUND = 0.35

MAX_STOCK_CATEGORY_WEIGHT = 0.95

STOCK_CATEGORIES = {
    "Technology Stocks",
    "Health Care Stocks",
    "Financial Stocks",
    "Industrial Stocks",
    "Consumer Discretionary Stocks",
    "Consumer Staples Stocks",
    "Energy Stocks",
    "Materials Stocks",
    "Utilities Stocks",
    "Real Estate Stocks",
    "Communication Services Stocks",
}